# Omer Javed
# FA15-BCS-100
### Week 1 day 7

### Imports in python

In [2]:
#if we want to include third party libraries we need to import them in our
# code with import keyword

import math

In [3]:
print('type of math is {}'.format(type(math)))

type of math is <class 'module'>


In [4]:
#math library contain alot of functions relevent to mathematics
# we can learn about any function or method of math using help function
# help(math)
math.pi #value of pi

3.141592653589793

In [5]:
math.log(32,5) # solve log

2.1533827903669653

In [52]:
#if we don't want to import whole library we can import specific methods
# then we can call them without class name we call them directly
from math import log,pi
print(log(32,5))
print(pi)


2.1533827903669653
3.141592653589793


In [53]:
# import with alias
import math as mt
import numpy as np
# we can use them with alias instead of using complete name of class
mt.pi

3.141592653589793

In [ ]:
from math import *

# * will import every thing from maths we can use all method without class

In [11]:
import numpy
# an other library 
numpyarray = numpy.random.randint(1,6,12)
# it will generate numpy array of 12 random numbers between 1 and 6  

In [23]:
numpyarray

array([2, 2, 2, 1, 2, 5, 4, 5, 3, 2, 3, 5])

In [12]:
type(numpyarray)

numpy.ndarray

In [14]:

#numpy have alot of built in methods we can know about them with help
# help(numpy)

In [15]:
numpyarray.mean() # mean value of all elements

3.0

In [31]:
numpyarray = numpyarray.tolist() #convert back to simple list
type(numpyarray)

list

#### Operator overloading
if we add something in simple list it give us error 
if we add something in numpy array it will add on each element

In [32]:
numpyarray 

[2, 2, 2, 1, 2, 5, 4, 5, 3, 2, 3, 5]

In [34]:
numpyarray + 10 

TypeError: can only concatenate list (not "int") to list

In [37]:
narray = numpyarray = numpy.random.randint(1,6,12)
narray

array([5, 2, 4, 5, 1, 3, 3, 5, 3, 1, 1, 5])

In [39]:
narray +10


array([15, 12, 14, 15, 11, 13, 13, 15, 13, 11, 11, 15])

In [42]:
 narray > 4  # return true or false for each element

array([ True, False, False,  True, False, False, False,  True, False,
       False, False,  True])

In [43]:
list2 = [[1,2,3],[6,5,4]] #2d list
list2

[[1, 2, 3], [6, 5, 4]]

In [45]:
nlist2 = numpy.asarray(list2) # convert input to numpy array
nlist2



array([[1, 2, 3],
       [6, 5, 4]])

In [46]:
type(nlist2)

numpy.ndarray

In [48]:
nlist2[1,-1] #get last element of second list

4

In [49]:
nlist2[0,-1] # get last element of first list

3