# Numpy


# Numpy Arrays
    Usually numpy is not packaged with python so we need to install them separately to use them they are not part of python so we import them from third partys libraries.
    Numpy came with rich variety of functions and routines which helps data scientists to various operations on lists and data.
### Installation of Numpy arrays
    For mac use command line and write : easy_install numpy 
    and for windows use command line and write : pip instal numpy
#### Difference between Numpy and python list
    NumPy arrays are  more efficient than Python lists when it comes to numeric operations. Numpy arrays are,in fact , specialized objects with extensive optimization Numpy code requires less explicit loops than equivalent Python code. This is based on vectorization.
### Numpy array object
    NumPy has a multi-dimensional array object called ndarray.It consist of two parts,
    => The actual data 
    => Some meta data (which describe about data)
### Advantages of NumPy arrays
    The NumPy array is, in general, homogeneous (there is a particular record array type that is heterogeneous)—the items in the array have to be of the same type. The advantage is that if we know that the items in an array are of the same type, it is easy to ascertain the storage size needed for the array.
    NumPy arrays are indexed just like Python, commencing from 0, Data types are represented by special objects.
    

In [ ]:
import numpy as np #import numpy np is refering word instead of using whole numpy we use np
a = [1,2,34,5]  # This is list
a = np.array(a)  #converting list into numpy
a

array([ 1,  2, 34,  5])

In [ ]:
a = [1,'a']
print(a)

b = [1,2,3,'a','b','c']
print(b)


In [ ]:
b = np.array(b)
b

Numpy Arrays

In [9]:
a = np.array(a)
a

array(['1', 'a'], dtype='|S11')

### subroutines for NumPy Arrays
    

In [14]:
# using arange function we can define a numpy array of any range.
import numpy as np
a = np.arange(5) #this function will generate array of 5 elements 0 to 4
a

array([0, 1, 2, 3, 4])

In [26]:
a.dtype # to get data type of array we use dtype function
# it will return integer vary from 32 to 64, 
# depend upon which version you have installed of python

dtype('int32')

In [23]:
a.shape 
# the vector has five components with values ranging from 0 to 4.
# The shape property of the array is a tuple;
# in this instance, a tuple of 1 element, 
# which holds the length in each dimension

(5L,)

### Creating a multidimensional array
    we have created one dimensional array  now we wil create 2D array in numpy

In [30]:
#we have created array which contain two arrays of two elements
m = np.array([np.arange(2),np.arange(2)]) 
m

array([[0, 1],
       [0, 1]])

In [31]:
m.shape #we get shape of array which tell us it is 2D array 

(2L, 2L)

In [32]:
m.dtype

dtype('int32')

In [37]:
a = np.array([[0,2],[3,4]])
a

array([[0, 2],
       [3, 4]])

### Selecting NumPy array elements
    Remember selecting arrays from previous tutorial it same like that
    Recall that the index number begin from 0

In [44]:
print(a[0,0]) #select elements from 0 element than 0 element
print(a[0,1]) #select elements from 0 element than 1 element 
print(a[1,0]) #select elements from 1 element than 0 element 
print(a[1,1]) #select elements from 1 element than 1 element 

0
2
3
4


In [47]:
a.dtype.itemsize


4

In [49]:
np.arange(7,dtype = 'f')  # initialize array using  data type argument

array([0., 1., 2., 3., 4., 5., 6.], dtype=float32)

In [52]:
np.arange(7,dtype = 'D') #this create array of complex numbers

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j])

### Slicing and Indexing
    Slicing of one-dimensional NumPy arrays works just like the slicing of standard  Python lists.

In [63]:
a = np.arange(9)
print(a) # complete array
print(a[3:7]) #selected index from 3 to 7
print(a[:7:2]) #third argument is step size ( array of even no.)
print(a[:7:3]) 
print(a[::-1]) # we can use negative indices and reverse the array:


[0 1 2 3 4 5 6 7 8]
[3 4 5 6]
[0 2 4 6]
[0 3 6]
[8 7 6 5 4 3 2 1 0]


### Array shapes
    

In [84]:
import numpy as np
b = np.arange(24).reshape(2,3,4)
#reshape function generate arrays of any shape in this example
# it generates array of 24 and split it in this way 
# divide into 2 parts => then divide each part into 3 parts => then 4 elements
print(b)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [90]:
print(b.ravel()) # print in one D
print(b.flatten()) #print array in 1D format
b.shape = (6,4) # we can reshape the array in any way like we use shape function
b               #6 elements each contains 4 elements

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [93]:
print(b)
b.transpose()  #transpose is very commonly used in matrices 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [101]:
b.resize((2,12)) #again resize the array using resize function
b


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

#### Stacking arrays
    Arrays can be stacked horizontally, depth wise or vertically.
    we use vstack(), dstack(), hstack(), column_stack(), row_stack(),  and concatenate() functions, for this goal:

In [103]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [106]:
b = a * 2 
#define a new array called b which contains elements of a multiplied by 2
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [114]:
#Horizontal stacking:
np.hstack((a,b)) # a and b are combined and elements are stacked horizontally

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [118]:
#we can attain same thing using concatenate() function:
np.concatenate((a,b), axis = 1)

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [120]:
#Vertical stacking:
np.vstack((a,b)) # a and b are combined and elements are stacked vertically

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [122]:
#we can attain same thing using concatenate() function:
np.concatenate((a,b), axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [127]:
#depth wise stacked 
np.dstack((a,b)) # elements are stacked depth wise

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

In [134]:
#column stacking used with 1D arrays

oned = np.arange(2)
print("one d array")
print(oned)
one_new = oned * 2
print("two d array")
print(one_new)
print("column stacked one D")
print(np.column_stack((oned , one_new)))
#two D array are column stacked same as hstack
print("column stacked two D array a,b")
print(np.column_stack((a,b)))

one d array
[0 1]
two d array
[0 2]
column stacked one D
[[0 0]
 [1 2]]
column stacked two D array a,b
[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]


In [136]:
np.column_stack((a,b)) == np.hstack((a,b))

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [139]:
#Row Stacking:
np.row_stack((oned,one_new))

array([[0, 1],
       [0, 2]])

### Spliting NumPy arrays
    Arrays can be split vertically, horizontally, or depth wise. The functions involved  are hsplit(), vsplit(), dsplit(), and split(). We can split arrays either into arrays of the same shape or indicate the location after which the split should happen. 

In [153]:
print("orignal array ")
print(a)
print("Aray with horizontal split()")
np.hsplit(a,3)

orignal array 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Aray with horizontal split()


[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [154]:
#We call split() function with additional argument axis = 1:
np.split(a,3,axis=1)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [156]:
#Vertical splitting:
np.vsplit(a,3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [158]:
# split() function, with axis=0, also splits along the vertical axis:
np.split(a,3, axis =0 )

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [163]:
#Depth-wise split
c = np.arange(27).reshape(3,3,3)
print(c)
np.dsplit(c,3)


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


[array([[[ 0],
         [ 3],
         [ 6]],
 
        [[ 9],
         [12],
         [15]],
 
        [[18],
         [21],
         [24]]]), array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]), array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]

### Some common routines Array attributes 
    * Demonstration with help of example
    * ndim gives the number of dimensions.
    * size holds the count of elements. 
    * itemsize returns the count of bytes for each element in the array.
    * If you require the full count of bytes the array needs, you can have a look  at nbytes.
    * The T property has the same result as the transpose() function.
    * Complex numbers in NumPy are represented by j. 
    * The real property returns to us the real part of the array.
    * The imag property holds the imaginary part of the array.
    * If the array holds complex numbers, then the data type will automatically  be complex as well.
    * The flat property gives back a numpy.flatiter object. This is the only means to get a flatiter object; we do not have access to a flatiter constructor. The flat iterator enables us to loop through an array as  if it were a flat array,

In [165]:
import numpy as np

b = np.arange(24).reshape(2,12)
b


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [172]:
print("dimension of array")
print(b.ndim) #print no of dimensions
print("total elements in array")
print(b.size) #total elements in array
print("size of each elements in byte")
print(b.itemsize)
print("total byte of array")
print(b.nbytes)
print("calculate total bytes manually")
print(b.size * b.itemsize)
print("Resize array")
b.resize(6,4)
print(b)
print("Transpose")
print(b.T)

dimension of array
2
total elements in array
24
size of each elements in byte
4
total byte of array
96
calculate total bytes manually
96
Resize array
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Transpose
[[ 0  4  8 12 16 20]
 [ 1  5  9 13 17 21]
 [ 2  6 10 14 18 22]
 [ 3  7 11 15 19 23]]


In [184]:
#elements with j is imaginary
b = np.array([1.j + 1 , 2.j + 3]) #initialize array with imaginary elements also
print("orinal Array")
print(b)
print("only real elements")
print(b.real)
print("only imaginary elements")
print(b.imag)
print("Datatype")
print(b.dtype)


orinal Array
[1.+1.j 3.+2.j]
only real elements
[1. 3.]
only imaginary elements
[1. 2.]
Datatype
complex128


In [202]:
b = np.arange(0,8,2).reshape(2,2)
print(b)
f = b.flat #flat the array and do operations on it
print(f)
for it in f:
    print(it)
print(f[2])

[[0 2]
 [4 6]]
0
2
4
6
4


In [203]:
b.flat[[1,3]]

array([2, 6])

In [204]:
print b
b.flat[[1,3]]=1 #change the elements from index 1 to 3
print b

[[0 2]
 [4 6]]
[[0 1]
 [4 1]]


### Converting arrays
    We can convert a NumPy array to a Python list with the tolist() function.

In [213]:
b = np.array([1.j +1 ,2.j + 2])
print(b)
b.tolist()
b


[1.+1.j 2.+2.j]


array([1.+1.j, 2.+2.j])

### some common functions


In [218]:
np.zeros((5,5)) #2d array of matrix of ones 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [222]:
np.linspace(0,5,10) 
#return an array of 10 evenly spaced numbers between 0 and 5 

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [223]:
np.eye(4) #return identity matrix of size 4 (useful in dealing algebra problems)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [224]:
np.random.rand(10) #return array of random number (Uniform distribution) 

array([0.11624438, 0.33653693, 0.27580459, 0.62531924, 0.58541636,
       0.32133879, 0.56337174, 0.95699477, 0.12769436, 0.47346377])

In [225]:
np.random.randn(10) #return array of random number (Normal distribution 

array([ 0.42351242, -0.06262439,  0.06068933, -0.26597303, -0.77355167,
       -0.26795356, -0.01062613,  0.12586726, -0.08145901,  0.73639803])

In [226]:
np.random.rand(5,5) #return matrix of random number 5x5

array([[0.3263649 , 0.15800579, 0.27848103, 0.55814183, 0.44517277],
       [0.53895051, 0.67444458, 0.16855594, 0.08201892, 0.70775566],
       [0.42426335, 0.60202699, 0.3929437 , 0.28581408, 0.82948694],
       [0.48312766, 0.22034033, 0.7049021 , 0.66916797, 0.31125661],
       [0.86609385, 0.78206262, 0.91562889, 0.68122873, 0.53965421]])

In [230]:
print(np.random.randint(1,100,5) )#return 5 random number in range of 1 and 10
print(np.random.randint(1,100) )#return a random number in range of 1 and 100

[37 16 86  2 93]
47


### Common operations in numPy

In [239]:
a = np.arange(10)
b = a * 2
print(a)
print(b)
print("Addition")
print(a + b)

print("Subtraction")
print(a - b)

print("Multpication")
print(a * b)

print("Power")
print(a ** 2)

print("division")
print(a / 100)

print("Mod")
print(a % 2)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]
Addition
[ 0  3  6  9 12 15 18 21 24 27]
Subtraction
[ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9]
Multpication
[  0   2   8  18  32  50  72  98 128 162]
Power
[ 0  1  4  9 16 25 36 49 64 81]
division
[0 0 0 0 0 0 0 0 0 0]
Mod
[0 1 0 1 0 1 0 1 0 1]


### Common NumPy Functions

In [243]:
print(a)
print(np.exp(a) )
print(np.max(a) )
print(np.sin(a))


[0 1 2 3 4 5 6 7 8 9]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
9
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
()
()
()
